### ISSUE TITLE
Error building the application (ng build -bh  ./ --prod --aot)

### ISSUE THREAD

**Issue by rojasjuniore** [maiyaporn/angular2-wizard#53]
ERROR in ./node_modules/angular2-wizard/src/wizard-step.component.ngfactory.ts
Module build failed: Error: /src/wizard-step.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/developer/Proyectos/metropolitano/metro/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/developer/Proyectos/metropolitano/metro/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
ERROR in ./node_modules/angular2-wizard/src/wizard.component.ngfactory.ts
Module build failed: Error: /Users/developer/Proyectos/metropolitano/metro/node_modules/angular2-wizard/src/wizard.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/developer/Proyectos/metropolitano/metro/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/developer/Proyectos/metropolitano/metro/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>

**Comment by mitschmidt** [comment]
Same error here - practically this makes the module unusable in an AOT context.

**Comment by maddy81818181** [comment]
It has a fix in angular-wizard version 0.4.4
